version: '3.8'
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: aguacate # password_root
      MYSQL_DATABASE: tfg-database
      MYSQL_USER: admin
      MYSQL_PASSWORD: aguacate # password_drupal
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    image: drupal:9.5-php8.1-apache
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_sites:/var/www/html/sites
      - drupal_themes:/var/www/html/themes
    environment:
      DRUPAL_DATABASE_HOST: database
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USER: admin
      DRUPAL_DATABASE_PASSWORD: aguacate

volumes:
  db_data:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes: