services:
  db:
    container_name: tfg-database
    restart: always
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    container_name: tfg-web
    image: drupal:10
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./profiles:/var/www/html/profiles
      - ./sites:/var/www/html/sites

volumes:
  db_data:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes: